### ISSUE TITLE
Freestanding

### ISSUE THREAD

**Issue by Immortalin** [edubart/euluna-lang#2]
Is it possible to output freestanding code with this? I.e. for stuff like os and kernel dev; minimal runtime and stdlib etc.

**Comment by edubart** [comment]
The language outputs C++ code, so would have same restrictions like mentioned in http://wiki.osdev.org/C%2B%2B (avoid exceptions, no RTTI, use malloc/free instead of new/delete)

In the future I may add a C code generator backend, relaxing these restrictions and targeting more compilers.

**Comment by edubart** [comment]
@Immortalin I would like to amend my answer, since this was asked much has changed. The project did generate C++ code, but that turned out to not be good choice and went stale for more than an year due to lack of time. The project at that time was named Euluna and did generate C++ code. Somewhere in last year I've rewrote all the project from scratch to generate straightforward readable C code and renamed the project to Nelua. At the moment it can generate freestanding code and its a goal to maintain this possibility, you just need to avoid using anything that would require APIs not available in your system, like you would do freestanding in C.
